@startuml


'https://plantuml.com/class-diagram

package commands {

    interface WhereCommand<T> {
       +where(condition: String): T
    }

    interface LimitCommand<T>{
        +limit(limit: Integer): T
    }

    interface OrderByCommand<T> {
        +orderBy(columns: String): T
        +orderBy((columns: String, order: Order): T
    }
    OrderByCommand -+ Order : <<has>>

    enum Order {
        ASC,
        DESC
    }
}

package select {
    interface FromQuery extends WhereCommand, OrderByCommand, LimitCommand, SqlQuery
    interface LimitQuery extends SqlQuery
    interface OrderByQuery extends LimitCommand
    interface SelectQuery {
        +from(table: String): FromQuery
    }

    class SelectQueryBuilder implements SelectQuery, FromQuery, LimitQuery, OrderByQuery, WhereQuery {
        -builder: StringBuilder{readOnly}
        -hasWhere: Boolean
        +SelectQueryBuilder(columns: String...)
        +from(table: String): FromQuery <<override>>
        +build(): String <<override>>
        +limit(limit: Integer): LimitQuery <<override>>
        +orderBy(column: String): OrderByQuery <<override>>
        +orderBy(column: String, order: Order): OrderByQuery <<override>>
        +where(condition: String): WhereQuery <<override>>
    }

    interface WhereQuery extends WhereCommand, OrderByCommand, LimitCommand, SqlQuery

}
interface SqlQuery {
    +build(): String
}

class SqlBuilder{
    {static}+select(columns: String...): SelectQuery
}


SqlBuilder ..> SelectQueryBuilder: <<creates>>



'Relation je suis pas sur'
WhereQuery --> SqlQuery
FromQuery --> SqlQuery
FromQuery --> WhereQuery
SelectQuery --> FromQuery

@enduml
